//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Groentenwijzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Groentenwijzer.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze app is gebaseerd op de groente- en fruitkalender van Velt vzw.
        ///
        ///Ontwikkeld door Peter Morlion (peter.morlion@live.be)
        ///Huidige versie: 1.4.0
        ///
        ///Updates:
        ///1.4.0
        ///- Franse versie
        ///- Wikipedie links voor fruit werken nu
        ///
        ///1.3.0
        ///- Aparte info-pagina via app-bar
        ///- Beoordeel link in app-bar
        ///
        ///1.2.1
        ///- Bugfix
        ///
        ///1.2.0
        ///- Doorklikken naar Wikipedia
        ///
        ///1.1.0
        ///- Fruit toegevoegd
        ///- Info pagina toegevoegd
        ///
        ///1.0.0
        ///- Enkel groenten.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alles.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorieën.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voedselkalender.
        /// </summary>
        public static string Foodcalendar {
            get {
                return ResourceManager.GetString("Foodcalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fruit.
        /// </summary>
        public static string Fruit {
            get {
                return ResourceManager.GetString("Fruit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiwi&apos;s.
        /// </summary>
        public static string Kiwis {
            get {
                return ResourceManager.GetString("Kiwis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opmerkingen over Voedselkalender app.
        /// </summary>
        public static string mailSubject {
            get {
                return ResourceManager.GetString("mailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rode bessen.
        /// </summary>
        public static string Rode_bessen {
            get {
                return ResourceManager.GetString("Rode_bessen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groenten.
        /// </summary>
        public static string Vegetables {
            get {
                return ResourceManager.GetString("Vegetables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://nl.wikipedia.org/wiki/{0}.
        /// </summary>
        public static string wikipediaBaseUri {
            get {
                return ResourceManager.GetString("wikipediaBaseUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwarte bessen.
        /// </summary>
        public static string Zwarte_bessen {
            get {
                return ResourceManager.GetString("Zwarte_bessen", resourceCulture);
            }
        }
    }
}
