//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Groentenwijzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WikipediaKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WikipediaKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Groentenwijzer.WikipediaKeys", typeof(WikipediaKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appel_(vrucht).
        /// </summary>
        public static string Appel_vrucht {
            get {
                return ResourceManager.GetString("Appel_vrucht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aubergine_(plant).
        /// </summary>
        public static string Aubergine_plant {
            get {
                return ResourceManager.GetString("Aubergine_plant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banaan_(vrucht).
        /// </summary>
        public static string Banaan_vrucht {
            get {
                return ResourceManager.GetString("Banaan_vrucht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Braam_(cultuurbraam).
        /// </summary>
        public static string Braam_cultuurbraam {
            get {
                return ResourceManager.GetString("Braam_cultuurbraam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kers_(fruit).
        /// </summary>
        public static string Kers_fruit {
            get {
                return ResourceManager.GetString("Kers_fruit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiwi_(fruit).
        /// </summary>
        public static string Kiwi_fruit {
            get {
                return ResourceManager.GetString("Kiwi_fruit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandarijn_(vrucht).
        /// </summary>
        public static string Mandarijn_vrucht {
            get {
                return ResourceManager.GetString("Mandarijn_vrucht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mango_(soort).
        /// </summary>
        public static string Mango_soort {
            get {
                return ResourceManager.GetString("Mango_soort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meloen_(vrucht).
        /// </summary>
        public static string Meloen_vrucht {
            get {
                return ResourceManager.GetString("Meloen_vrucht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paddenstoel_(schimmel).
        /// </summary>
        public static string Paddenstoel_schimmel {
            get {
                return ResourceManager.GetString("Paddenstoel_schimmel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peer_(vrucht).
        /// </summary>
        public static string Peer_vrucht {
            get {
                return ResourceManager.GetString("Peer_vrucht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ui_(plant).
        /// </summary>
        public static string Ui_plant {
            get {
                return ResourceManager.GetString("Ui_plant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wortel_(groente).
        /// </summary>
        public static string Wortel_groente {
            get {
                return ResourceManager.GetString("Wortel_groente", resourceCulture);
            }
        }
    }
}
